title: Yajur Healthcare AI
email: connect@yajur.ai
description: "The Medical Data Structure Company"
url: "https://msharmas-yajur.github.io"
baseurl: "/yajur-ai"

# Hydra Theme Configuration (Manual)
logo: /assets/logo.png

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sass-converter

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

sass:
  sass_dir: _sass
  style: :expanded
